version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias..."
      - chmod +x backend/mvnw
      
  pre_build:
    commands:
      - echo "Preparando build..."
      
  build:
    commands:
      - echo "Construyendo aplicación..."
      - ./backend/mvnw -f backend/pom.xml clean package -DskipTests
      - echo "Build completado"
      
  post_build:
    commands:
      - echo "Post-build completado"
      - ls -la backend/target/

artifacts:
  files:
    - backend/target/imageclec-backend-0.0.1-SNAPSHOT.jar
    - Procfile
    - .ebextensions/**/*
  discard-paths: no 